name: Build on macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos-12:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        build-type: [ Debug, Release ]
        xcode: [ 13.4.1, 13.4, 13.3.1, 13.2.1, 13.1 ]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DTAOF_BUILD_TESTS=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --parallel --output-on-failure
  macos-11:
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        build-type: [ Debug, Release ]
        xcode: [ 13.2.1, 13.1, 12.5.1, 12.4 ] # TODO : Investigate why 13.0 isn't working
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DTAOF_BUILD_TESTS=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --parallel --output-on-failure